adding minio as docker

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,7 +28,21 @@ jobs:
       packages: write
       security-events: write
       actions: read
-    
+
+# not sure should i use minio as a service or docker i will use docker for now       
+    # services:
+    #   minio:
+    #     image: minio/minio
+    #     ports:
+    #       - 9000:9000
+    #       - 9001:9001
+    #     env:
+    #       MINIO_ROOT_USER: minioadmin
+    #       MINIO_ROOT_PASSWORD: minioadmin
+    #     options: --name=minio --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1" --health-interval 10s --health-timeout 5s --health-retries 3
+    #     volumes:
+    #       - minio-data:/data  
+        
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -133,8 +147,17 @@ jobs:
           push: true
           tags: mawlstace/beekeeper-api:latest,mawlstace/beekeeper-api:${{ github.sha }}
           cache-from: type=registry,ref=mawlstace/beekeeper-api:buildcache
-          cache-to: type=registry,ref=mawlstace/beekeeper-api:buildcache,mode=max
-
+          cache-to: type=registry,ref=mawlstace/beekeeper-api:buildcache,mode=max      
+      - name: Start MinIO
+        run: |
+          docker run -d --name minio \
+            -p 9000:9000 -p 9001:9001 \
+            -e MINIO_ROOT_USER=minioadmin \
+            -e MINIO_ROOT_PASSWORD=minioadmin \
+            minio/minio server /data --console-address ":9001"
+          echo "Waiting for MinIO to start..."
+          sleep 10
+          curl -f http://localhost:9000/minio/health/live || exit 1
       - name: Integration Tests
         run: |
           docker run -d -p 8000:8000 mawlstace/beekeeper-api:latest
@@ -145,9 +168,6 @@ jobs:
               curl -f http://localhost:8000/version
               curl -f http://localhost:8000/temperature
               curl -f http://localhost:8000/metrics
-          # # Additional API tests
-          # pytest integration_tests/
-
       - name: Run integration tests
         continue-on-error: true
         run: |
